#ddev-generated
services:
  alfresco:
    image: ${ALFRESCO_IMAGE:-alfresco/alfresco-content-repository-community:23.2.1}
    container_name: ddev-${DDEV_SITENAME}-alfresco
    hostname: ${DDEV_SITENAME}-alfresco
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      VIRTUAL_HOST: ${DDEV_HOSTNAME}
      HTTP_EXPOSE: 8080:8080
      HTTPS_EXPOSE: 8081:8080
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Xms1500m
        -Xmx1500m
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres-alfresco:5432/alfresco
        -Dindex.subsystem.name=noindex
        -Dmessaging.subsystem.autoStart=false
        -Dtransform.service.enabled=false
        -Dlocal.transform.service.enabled=false
        -Dlegacy.transform.service.enabled=false
        -Dcsrf.filter.enabled=false
        -Dalfresco.protocol=https
        -Dalfresco.host=${DDEV_SITENAME}.${DDEV_TLD}
        -Dalfresco.port=8081
        -Dshare.protocol=https
        -Dshare.host=${DDEV_SITENAME}.${DDEV_TLD}
        -Dshare.port=8081
    volumes:
      - alfresco-data:/usr/local/tomcat/alf_data
      - .:/mnt/ddev_config
      - ddev-global-cache:/mnt/ddev-global-cache
    depends_on:
      postgres-alfresco:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 400s

  postgres-alfresco:
    image: ${POSTGRES_IMAGE:-postgres:15.7}
    container_name: ddev-${DDEV_SITENAME}-postgres-alfresco
    hostname: ${DDEV_SITENAME}-postgres-alfresco
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
      POSTGRES_DB: alfresco
      PGUSER: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-alfresco-data:/var/lib/postgresql/data
      - .:/mnt/ddev_config

volumes:
  alfresco-data:
  postgres-alfresco-data:
